### PR TITLE
Refactor with HTML5 features and improved responsiveness

### PR DESCRIPTION
**Pull request by Alexander-Prime**
Saw an opportunity to contribute here when I read that there were no plans to support IE. I've made an effort to preserve the _intent_ of the design while improving on some shortcomings, mostly in regards to scaling on small devices. There's some `display: flex` bling here and there to keep the browser's sizing well-behaved.

There's also a lot of HTML that's been cut out and simplified. I'm no good with Javascript, so I had to figure out what needed to be left in place by trial and error. Might've missed something.

Here's a before-and-after comparison, taken from a 7" Android tablet.

before-after

The difference is even more pronounced on mobile.

I can't figure out how this is meant to be deployed, so the changes are only in the `src/` directory, which I assume propagates somehow to the top-level site.

### CODE REVIEW

**Comment by XrXr** [comment]
Thanks for the PR! 
I like the idea overall, in fact I was going to do something similar in the future, but there are some problems with the PR.
1. I don't like how the page makes a scroll bar on desktop on little zoom. It also creates 
   empty spot on the bottom when the zoom is 100%
   
   On desktop (1920x1080) 
   Bad
2. The credit row is not spread out correctly on mobile Safari
   
   Mobile Safari
3. The countdown text should be black when the streamer is not live. `.desguise` and `prefix` class are used for that.

**Comment by XrXr** [comment]
There are also stylistic issues with the PR. It uses tabs instead of spaces. This makes the style inconsistent and messes up the diff. Tab-width is 2 spaces for HTML, and 4 spaces for CSS.

`<head>` and `<html>` and `<body>` are all missing in index.html, they need to be there. Also, the Google Analytics code is unnecessary in src, they will be added when the changes are deployed.

Thanks!

**Comment by Alexander-Prime** [comment]
`<head>`, `<html>`, and `<body>` are optional in spec; removing them did not affect rendering or validation, so I left them out. Are they needed for something that I've overlooked?

The rest of the problems are just me being careless. I'll go fix them now.

**Comment by XrXr** [comment]
It's good practice to include them. It's fine when prototyping though. Also, Bootstrap requires
`<html lang="en">`

**Comment by Alexander-Prime** [comment]
Bootstrap was being almost completely overwritten by site styles, so I copied a couple from it and removed the reference.

I'll put `<html>` et al back in anyway.

**Comment by Alexander-Prime** [comment]
I don't have a device to test mobile Safari locally, but a second look at [Can I use](http://caniuse.com/#search=flexbox) shows that it expects flexbox styles to be prefixed. I have no idea why the site links appear to be working, so I've just added the prefixed styles as an attempted fix.

**Comment by XrXr** [comment]
Nice! remember to change the tab-size accordingly.

**Comment by Alexander-Prime** [comment]
Oh jeez, my editor messed up the HTML again, didn't it?

Kate (that is, the text editor, not the person) doesn't have separate tab profiles per-language. I fixed the HTML, then the CSS, and it broke the HTML again. :<

Fixing it now.

**Comment by Alexander-Prime** [comment]
As a side note, do you have webmaster access to http://wheniskate.eu? Loading the site via `<iframe>` is making the browser ignore the icon and title.

**Comment by XrXr** [comment]
I don't have access to the domains unfortunately. They are managed by @MrStatistX on Twitter.

**Comment by XrXr** [comment]
I tried the latest version out, and the credit row is not centered properly on desktop and mobile
Bad
Also children of `<body>` and `<head>` should be intended one level :)
Another thing is the Youtube logo seems to be cropped, if you look carefully. They are pretty anal about their logo usage.. `0.9em` fixes it

**Comment by Alexander-Prime** [comment]
Got your name centered. My flex-fu is not strong enough to make this look good as a single line on all sizes, so I had the test and source links break onto a second line in the 700px query.

Fixed tabs again again, maybe? I feel like I might be misunderstanding something, so I tried to match the style of the existing index.html. Can you tell I'm used to ignoring these? :P

**Comment by Alexander-Prime** [comment]
My instinct is that this is a raster scaling side-effect, but the logos look good at 90% anyway. Fix'd.

**Comment by XrXr** [comment]
Looks good to me! There are still a few small problems, like the changes to the images (I don't want to resize the logos since they are anal about it) and the cursor when hovering the count down (should be the default cursor) and the trailing white spaces (burn them with fire). I will fix those manually.

**Pull request merged**
